# ==============================================================================
# Prepare GAEZ v5 Package Data
#
# This script extracts data objects from the original script and saves them
# as package data in the data/ directory
# ==============================================================================

library(dplyr)
library(tidyr)
library(tibble)

# ==============================================================================
# GAEZ v5 Variables Table
# ==============================================================================

gaez_variables <- tribble(
  ~theme_number,
  ~theme_name,
  ~sub_theme_name,
  ~variable_code,
  ~variable_name,
  ~data_folder,
  ~data_code,
  1,
  "Land and Water Resources",
  "Agro-Ecological Zones",
  "AEZ57",
  "AEZ classification by climate, soil, terrain, land cover (Global - ~1 km - 57 classes)",
  "MAP",
  "AEZ57",
  1,
  "Land and Water Resources",
  "Agro-Ecological Zones",
  "AEZ33",
  "AEZ classification by climate, soil, terrain, land cover (Global - ~1 km - 33 classes)",
  "MAP",
  "AEZ33-1KM",
  1,
  "Land and Water Resources",
  "Agro-Ecological Zones",
  "AEZ33",
  "AEZ classification by climate, soil, terrain, land cover (Global - ~10 km - 33 classes)",
  "MAP",
  "AEZ33",
  1,
  "Land and Water Resources",
  "Land Cover",
  "LR-LCC",
  "Share of land cover class",
  "MAP",
  "LR-LCC",
  1,
  "Land and Water Resources",
  "Soil Resources",
  "HWSDV201",
  "Harmonized World Soils Database version 2.01 - WRB Soil Group names",
  "MAP",
  "HWSDV201",
  1,
  "Land and Water Resources",
  "Terrain Resources",
  "SOILFER.ELEV-ALOS-30M",
  "Median elevation",
  "MAP",
  "SOILFER.ELEV-ALOS-30M",
  1,
  "Land and Water Resources",
  "Terrain Resources",
  "SOILFER.SLOPE-MED",
  "Median slope class",
  "MAP",
  "SOILFER.SLOPE-MED",
  1,
  "Land and Water Resources",
  "Exclusion Areas",
  "EXCL",
  "Exclusion areas",
  "MAP",
  "EXCL",
  1,
  "Land and Water Resources",
  "Water Resources",
  "LR-IRR",
  "Share of irrigated land",
  "MAP",
  "LR-IRR",
  2,
  "Agro-climatic Resources",
  "Climate Classification",
  "RES01-MC3",
  "Classification by thermal climates and thermal zones",
  "MAPSET",
  "RES01-MC3",
  2,
  "Agro-climatic Resources",
  "Climate Classification",
  "RES01-KG2",
  "Koeppen-Geiger (2-character) classification",
  "MAPSET",
  "RES01-KG2",
  2,
  "Agro-climatic Resources",
  "Climate Classification",
  "RES01-KG3",
  "Koeppen-Geiger (3-character) classification",
  "MAPSET",
  "RES01-KG3",
  2,
  "Agro-climatic Resources",
  "Climate Classification",
  "RES01-MCR",
  "Multi-cropping class (rain-fed)",
  "MAPSET",
  "RES01-MCR",
  9,
  "Agro-climatic Resources",
  "Climate Classification",
  "RES01-MCR-TS",
  "Multi-cropping class (rain-fed) - Time series",
  "MAPSET",
  "RES01-MCR-TS",
  2,
  "Agro-climatic Resources",
  "Climate Classification",
  "RES01-MCI",
  "Multi-cropping class (with irrigation)",
  "MAPSET",
  "RES01-MCI",
  9,
  "Agro-climatic Resources",
  "Climate Classification",
  "RES01-MCI-TS",
  "Multi-cropping class (with irrigation) - Time series",
  "MAPSET",
  "RES01-MCI-TS",
  2,
  "Agro-climatic Resources",
  "Climate Classification",
  "RES01-PFR",
  "Permafrost zones",
  "MAPSET",
  "RES01-PFR",
  2,
  "Agro-climatic Resources",
  "Climate Classification",
  "RES01-MCL",
  "Thermal Climates (temperatures reduced to sea level)",
  "MAPSET",
  "RES01-MCL",
  2,
  "Agro-climatic Resources",
  "Climate Classification",
  "RES01-MC2",
  "Thermal Zones",
  "MAPSET",
  "RES01-MC2",
  2,
  "Agro-climatic Resources",
  "Climate Classification",
  "RES01-LGP",
  "Total number of growing period days class",
  "MAPSET",
  "RES01-LGP",
  9,
  "Agro-climatic Resources",
  "Climate Classification",
  "RES01-LGP-TS",
  "Total number of growing period days class - Time series",
  "MAPSET",
  "RES01-LGP-TS",
  2,
  "Agro-climatic Resources",
  "Growing Period",
  "RES01-LGB",
  "Beginning date of longest component LGP",
  "MAPSET",
  "RES01-LGB",
  9,
  "Agro-climatic Resources",
  "Growing Period",
  "RES01-LGB-TS",
  "Beginning date of longest component LGP - Time series",
  "MAPSET",
  "RES01-LGB-TS",
  2,
  "Agro-climatic Resources",
  "Growing Period",
  "RES01-LD1",
  "Length of longest component LGP",
  "MAPSET",
  "RES01-LD1",
  9,
  "Agro-climatic Resources",
  "Growing Period",
  "RES01-LD1-TS",
  "Length of longest component LGP - Time series",
  "MAPSET",
  "RES01-LD1-TS",
  2,
  "Agro-climatic Resources",
  "Growing Period",
  "RES01-NDD",
  "Longest period of consecutive dry days in temperature growing period LGPt=5",
  "MAPSET",
  "RES01-NDD",
  9,
  "Agro-climatic Resources",
  "Growing Period",
  "RES01-NDD-TS",
  "Longest period of consecutive dry days in temperature growing period LGPt=5 - Time series",
  "MAPSET",
  "RES01-NDD-TS",
  2,
  "Agro-climatic Resources",
  "Growing Period",
  "RES01-NP2",
  "Net primary production (rain-fed)",
  "MAPSET",
  "RES01-NP2",
  9,
  "Agro-climatic Resources",
  "Growing Period",
  "RES01-NP2-TS",
  "Net primary production (rain-fed) - Time series",
  "MAPSET",
  "RES01-NP2-TS",
  2,
  "Agro-climatic Resources",
  "Growing Period",
  "RES01-NP1",
  "Net primary production (with irrigation)",
  "MAPSET",
  "RES01-NP1",
  9,
  "Agro-climatic Resources",
  "Growing Period",
  "RES01-NP1-TS",
  "Net primary production (with irrigation) - Time series",
  "MAPSET",
  "RES01-NP1-TS",
  2,
  "Agro-climatic Resources",
  "Growing Period",
  "RES01-LGD",
  "Total number of growing period days",
  "MAPSET",
  "RES01-LGD",
  9,
  "Agro-climatic Resources",
  "Growing Period",
  "RES01-LGD-TS",
  "Total number of growing period days - Time series",
  "MAPSET",
  "RES01-LGD-TS",
  2,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RID",
  "Annual P/PET ratio",
  "MAPSET",
  "RES01-RID",
  9,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RID-TS",
  "Annual P/PET ratio - Time series",
  "MAPSET",
  "RES01-RID-TS",
  2,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-PRC",
  "Annual precipitation",
  "MAPSET",
  "RES01-PRC",
  9,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-PRC-TS",
  "Annual precipitation - Time series",
  "MAPSET",
  "RES01-PRC-TS",
  2,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RFM",
  "Modified Fournier Index",
  "MAPSET",
  "RES01-RFM",
  9,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RFM-TS",
  "Modified Fournier Index - Time series",
  "MAPSET",
  "RES01-RFM-TS",
  2,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RI2",
  "P/PET for days with Ta > 5 °C",
  "MAPSET",
  "RES01-RI2",
  9,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RI2-TS",
  "P/PET for days with Ta > 5 °C - Time series",
  "MAPSET",
  "RES01-RI2-TS",
  2,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RQ2",
  "Quarterly P/PET ratio (April-June)",
  "MAPSET",
  "RES01-RQ2",
  9,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RQ2-TS",
  "Quarterly P/PET ratio (April-June) - Time series",
  "MAPSET",
  "RES01-RQ2-TS",
  2,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RQ1",
  "Quarterly P/PET ratio (January-March)",
  "MAPSET",
  "RES01-RQ1",
  9,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RQ1-TS",
  "Quarterly P/PET ratio (January-March) - Time series",
  "MAPSET",
  "RES01-RQ1-TS",
  2,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RQ3",
  "Quarterly P/PET ratio (July-September)",
  "MAPSET",
  "RES01-RQ3",
  9,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RQ3-TS",
  "Quarterly P/PET ratio (July-September) - Time series",
  "MAPSET",
  "RES01-RQ3-TS",
  2,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RQ4",
  "Quarterly P/PET ratio (October-December)",
  "MAPSET",
  "RES01-RQ4",
  9,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RQ4-TS",
  "Quarterly P/PET ratio (October-December) - Time series",
  "MAPSET",
  "RES01-RQ4-TS",
  2,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-ETA",
  "Reference actual evapotranspiration",
  "MAPSET",
  "RES01-ETA",
  9,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-ETA-TS",
  "Reference actual evapotranspiration - Time series",
  "MAPSET",
  "RES01-ETA-TS",
  2,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-ET0",
  "Reference potential evapotranspiration",
  "MAPSET",
  "RES01-ET0",
  9,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-ET0-TS",
  "Reference potential evapotranspiration - Time series",
  "MAPSET",
  "RES01-ET0-TS",
  2,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RIS",
  "Seasonal P/PET ratio (*100) in summer (April-September in northern hemisphere)",
  "MAPSET",
  "RES01-RIS",
  9,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RIS-TS",
  "Seasonal P/PET ratio (*100) in summer (April-September in northern hemisphere) - Time series",
  "MAPSET",
  "RES01-RIS-TS",
  2,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RIW",
  "Seasonal P/PET ratio (*100) in winter (October-March in northern hemisphere)",
  "MAPSET",
  "RES01-RIW",
  9,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-RIW-TS",
  "Seasonal P/PET ratio (*100) in winter (October-March in northern hemisphere) - Time series",
  "MAPSET",
  "RES01-RIW-TS",
  2,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-NDR",
  "Total number of rain days",
  "MAPSET",
  "RES01-NDR",
  9,
  "Agro-climatic Resources",
  "Moisture Regime",
  "RES01-NDR-TS",
  "Total number of rain days - Time series",
  "MAPSET",
  "RES01-NDR-TS",
  2,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-FST",
  "Air frost number",
  "MAPSET",
  "RES01-FST",
  9,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-FST-TS",
  "Air frost number - Time series",
  "MAPSET",
  "RES01-FST-TS",
  2,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-TS3",
  "Annual temperature sum for days with Ta>10 °C",
  "MAPSET",
  "RES01-TS3",
  9,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-TS3-TS",
  "Annual temperature sum for days with Ta>10 °C - Time series",
  "MAPSET",
  "RES01-TS3-TS",
  2,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-TS2",
  "Annual temperature sum for days with Ta>5 °C",
  "MAPSET",
  "RES01-TS2",
  9,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-TS2-TS",
  "Annual temperature sum for days with Ta>5 °C - Time series",
  "MAPSET",
  "RES01-TS2-TS",
  2,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-TMP",
  "Mean annual temperature",
  "MAPSET",
  "RES01-TMP",
  9,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-TMP-TS",
  "Mean annual temperature - Time series",
  "MAPSET",
  "RES01-TMP-TS",
  2,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-X35",
  "Number of days with Tmax > 35 °C",
  "MAPSET",
  "RES01-X35",
  9,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-X35-TS",
  "Number of days with Tmax > 35 °C - Time series",
  "MAPSET",
  "RES01-X35-TS",
  2,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-X40",
  "Number of days with Tmax > 40 °C",
  "MAPSET",
  "RES01-X40",
  9,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-X40-TS",
  "Number of days with Tmax > 40 °C - Time series",
  "MAPSET",
  "RES01-X40-TS",
  2,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-X45",
  "Number of days with Tmax > 45 °C",
  "MAPSET",
  "RES01-X45",
  9,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-X45-TS",
  "Number of days with Tmax > 45 °C - Time series",
  "MAPSET",
  "RES01-X45-TS",
  2,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-N00",
  "Number of days with Tmin < 0 °C",
  "MAPSET",
  "RES01-N00",
  9,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-N00-TS",
  "Number of days with Tmin < 0 °C - Time series",
  "MAPSET",
  "RES01-N00-TS",
  2,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-N10",
  "Number of days with Tmin < 10 °C",
  "MAPSET",
  "RES01-N10",
  9,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-N10-TS",
  "Number of days with Tmin < 10 °C - Time series",
  "MAPSET",
  "RES01-N10-TS",
  2,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-N15",
  "Number of days with Tmin < 15 °C",
  "MAPSET",
  "RES01-N15",
  9,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-N15-TS",
  "Number of days with Tmin < 15 °C - Time series",
  "MAPSET",
  "RES01-N15-TS",
  2,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-WDE",
  "Reference evapotranspiration deficit",
  "MAPSET",
  "RES01-WDE",
  9,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-WDE-TS",
  "Reference evapotranspiration deficit - Time series",
  "MAPSET",
  "RES01-WDE-TS",
  2,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-FSS",
  "Snow-adjusted air frost number",
  "MAPSET",
  "RES01-FSS",
  9,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-FSS-TS",
  "Snow-adjusted air frost number - Time series",
  "MAPSET",
  "RES01-FSS-TS",
  2,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-LT3",
  "Temperature growing period; number of days with Ta > 10 °C",
  "MAPSET",
  "RES01-LT3",
  9,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-LT3-TS",
  "Temperature growing period; number of days with Ta > 10 °C - Time series",
  "MAPSET",
  "RES01-LT3-TS",
  2,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-LT4",
  "Temperature growing period; number of days with Ta > 20 °C",
  "MAPSET",
  "RES01-LT4",
  9,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-LT4-TS",
  "Temperature growing period; number of days with Ta > 20 °C - Time series",
  "MAPSET",
  "RES01-LT4-TS",
  2,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-LT5",
  "Temperature growing period; number of days with Ta > 30 °C",
  "MAPSET",
  "RES01-LT5",
  9,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-LT5-TS",
  "Temperature growing period; number of days with Ta > 30 °C - Time series",
  "MAPSET",
  "RES01-LT5-TS",
  2,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-LT2",
  "Temperature growing period; number of days with Ta > 5 °C",
  "MAPSET",
  "RES01-LT2",
  9,
  "Agro-climatic Resources",
  "Thermal Regime",
  "RES01-LT2-TS",
  "Temperature growing period; number of days with Ta > 5 °C - Time series",
  "MAPSET",
  "RES01-LT2-TS",
  3,
  "Agro-climatic Potential Yield",
  "Agro-Climatic Yield",
  "RES02-YLD",
  "Agro-climatic potential yield",
  "MAPSET",
  "RES02-YLD",
  3,
  "Agro-climatic Potential Yield",
  "Constraint Factors",
  "RES02-FC1",
  "Crop yield constraint factor '1' (thermal)",
  "MAPSET",
  "RES02-FC1",
  3,
  "Agro-climatic Potential Yield",
  "Constraint Factors",
  "RES02-FC2",
  "Crop yield constraint factor '2' (moisture)",
  "MAPSET",
  "RES02-FC2",
  3,
  "Agro-climatic Potential Yield",
  "Constraint Factors",
  "RES02-FC3",
  "Crop yield constraint factor '3' (agro-climatic)",
  "MAPSET",
  "RES02-FC3",
  3,
  "Agro-climatic Potential Yield",
  "Constraint Factors",
  "RES02-FC0",
  "Total climate related crop yield constraint factor '0'",
  "MAPSET",
  "RES02-FC0",
  3,
  "Agro-climatic Potential Yield",
  "Growth Cycle Attributes",
  "RES02-CBD",
  "Beginning of crop growth cycle (day)",
  "MAPSET",
  "RES02-CBD",
  3,
  "Agro-climatic Potential Yield",
  "Growth Cycle Attributes",
  "RES02-WDE",
  "Crop water deficit (mm)",
  "MAPSET",
  "RES02-WDE",
  3,
  "Agro-climatic Potential Yield",
  "Growth Cycle Attributes",
  "RES02-TSC",
  "Crop-specific accumulated temperature during crop growth cycle",
  "MAPSET",
  "RES02-TSC",
  3,
  "Agro-climatic Potential Yield",
  "Growth Cycle Attributes",
  "RES02-ETA",
  "Crop-specific actual evapotranspiration (mm)",
  "MAPSET",
  "RES02-ETA",
  3,
  "Agro-climatic Potential Yield",
  "Growth Cycle Attributes",
  "RES02-CYL",
  "Length of crop growth cycle (days)",
  "MAPSET",
  "RES02-CYL",
  3,
  "Agro-climatic Potential Yield",
  "Land Utilization Types (LUT) Selection",
  "RES02-IDX",
  "Selected LUT sequence number",
  "MAPSET",
  "RES02-IDX",
  4,
  "Suitability and Attainable Yield",
  "Agro-ecological Attainable Yield",
  "RES05-YX",
  "Average attainable yield of best occurring suitability class in grid cell",
  "MAPSET",
  "RES05-YXX",
  4,
  "Suitability and Attainable Yield",
  "Agro-ecological Attainable Yield",
  "RES05-YC",
  "Average attainable yield of current cropland (10 km)",
  "MAPSET",
  "RES05-YCX",
  4,
  "Suitability and Attainable Yield",
  "Agro-ecological Attainable Yield",
  "RES05-YC",
  "Average attainable yield of current cropland (1 km)",
  "MAPSET",
  "RES05-YCX30AS",
  4,
  "Suitability and Attainable Yield",
  "Agro-ecological Attainable Yield",
  "RES05-YL",
  "Output density i.e. yield (potential production divided by total grid cell area) (10 km)",
  "MAPSET",
  "RES05-YLX",
  4,
  "Suitability and Attainable Yield",
  "Agro-ecological Attainable Yield",
  "RES05-YL",
  "Output density i.e. yield (potential production divided by total grid cell area) (1 km)",
  "MAPSET",
  "RES05-YLX30AS",
  4,
  "Suitability and Attainable Yield",
  "Suitability Class",
  "RES05-SI",
  "Crop suitability index in classes; all land in grid cell (10 km)",
  "MAPSET",
  "RES05-SIX",
  4,
  "Suitability and Attainable Yield",
  "Suitability Class",
  "RES05-SI",
  "Crop suitability index in classes; all land in grid cell (1 km)",
  "MAPSET",
  "RES05-SIX30AS",
  4,
  "Suitability and Attainable Yield",
  "Suitability Class",
  "RES05-SC",
  "Crop suitability index in classes; current cropland in grid cell (10 km)",
  "MAPSET",
  "RES05-SCX",
  4,
  "Suitability and Attainable Yield",
  "Suitability Class",
  "RES05-SC",
  "Crop suitability index in classes; current cropland in grid cell (1 km)",
  "MAPSET",
  "RES05-SCX30AS",
  4,
  "Suitability and Attainable Yield",
  "Suitability Index",
  "RES05-SX1",
  "Share of grid cell assessed as VS or S (range 0 – 10000)",
  "MAPSET",
  "RES05-SX1",
  4,
  "Suitability and Attainable Yield",
  "Suitability Index",
  "RES05-SX2",
  "Share of VS+S+MS land in grid cell (range 0 – 10000)",
  "MAPSET",
  "RES05-SX2",
  4,
  "Suitability and Attainable Yield",
  "Suitability Index",
  "RES05-SX3",
  "Share of VS+S+MS+mS land in grid cell (range 0 – 10000)",
  "MAPSET",
  "RES05-SX3",
  4,
  "Suitability and Attainable Yield",
  "Suitability Index",
  "RES05-SX",
  "Suitability index  range (0 – 10000); all land in grid cell (10 km)",
  "MAPSET",
  "RES05-SXX",
  4,
  "Suitability and Attainable Yield",
  "Suitability Index",
  "RES05-SX",
  "Suitability index  range (0 – 10000); all land in grid cell (1 km)",
  "MAPSET",
  "RES05-SXX30AS",
  4,
  "Suitability and Attainable Yield",
  "Suitability Index",
  "RES05-SU",
  "Suitability index  range (0 – 10000); current cropland in grid cell",
  "MAPSET",
  "RES05-SUX",
  4,
  "Suitability and Attainable Yield",
  "Crop Water Indicators",
  "RES05-ETL",
  "Actual crop evapotranspiration (excluding irrigation), average for grid cell",
  "MAPSET",
  "RES05-ETL",
  4,
  "Suitability and Attainable Yield",
  "Crop Water Indicators",
  "RES05-ETC",
  "Actual crop evapotranspiration (excluding irrigation), for current cropland",
  "MAPSET",
  "RES05-ETC",
  4,
  "Suitability and Attainable Yield",
  "Crop Water Indicators",
  "RES05-WDC",
  "Water deficit/net irrigation requirement during crop cycle, current cropland",
  "MAPSET",
  "RES05-WDC",
  4,
  "Suitability and Attainable Yield",
  "Crop Water Indicators",
  "RES05-WDL",
  "Water deficit/net irrigation requirement during crop cycle, total grid cell",
  "MAPSET",
  "RES05-WDL",
  5,
  "Actual Yields and Production",
  "Area, Yield and Production",
  "RES06-HAR",
  "Harvested area",
  "MAPSET",
  "RES06-HAR",
  5,
  "Actual Yields and Production",
  "Area, Yield and Production",
  "RES06-PRD",
  "Production",
  "MAPSET",
  "RES06-PRD",
  5,
  "Actual Yields and Production",
  "Area, Yield and Production",
  "RES06-YLD",
  "Yield",
  "MAPSET",
  "RES06-YLD",
  5,
  "Actual Yields and Production",
  "Aggregate Crop Production Value",
  "RES06-VAL",
  "Total crop production volume",
  "MAPSET",
  "RES06-VAL",
  6,
  "Yield and Production Gaps",
  "Yield Achievement Ratio",
  "RES07-YGA-CL",
  "Cropwise Yield Achievement Ratio",
  "MAPSET",
  "RES07-YGA-CL",
  6,
  "Yield and Production Gaps",
  "Yield Achievement Ratio",
  "RES07-H-CL",
  "Aggregate Yield Achievement Ratio",
  "MAPSET",
  "RES07-H-CL",
  6,
  "Yield and Production Gaps",
  "Production Gap",
  "RES07-QGA",
  "Cropwise Apparent Production Gap",
  "MAPSET",
  "RES07-QGA"
)

# ==============================================================================
# GAEZ v5 Crop Codes (Modules II-VI combined)
# ==============================================================================

# Module II (4-letter codes) - Theme 3
gaez_crops_m2 <- tribble(
  ~gaez_crop_code, ~name, ~gaez_crop_group,
  "ALFA", "Alfalfa", "Fodder crops",
  "BANA", "Banana", "Fruits",
  "BARL", "Barley (the better of sbrl and wbrl)", "Cereals",
  "BHSG", "Biomass highland sorghum", "Bioenergy feedstocks",
  "BLSG", "Biomass lowland sorghum", "Bioenergy feedstocks",
  "BSRG", "Biomass sorghum (best blsg, bhsg and btsg)", "Bioenergy feedstocks",
  "BTSG", "Biomass temperate sorghum", "Bioenergy feedstocks",
  "BRCH", "Brachiaria", "Bioenergy feedstocks",
  "BCKW", "Buckwheat", "Cereals",
  "CABB", "Cabbage", "Vegetables",
  "COCC", "Cacao (comum)", "Narcotics and stimulants",
  "COCH", "Cacao (hybrid)", "Narcotics and stimulants",
  "COCO", "Cacao (the better of comum and hybrid)", "Narcotics and stimulants",
  "CAME", "Camelina, all types", "Bioenergy feedstocks",
  "CAMW", "Camelina, autumn and winter types", "Bioenergy feedstocks",
  "CAMSP", "Camelina, spring types", "Bioenergy feedstocks",
  "CARI", "Carinata", "Bioenergy feedstocks",
  "CARIS", "Carinata spring types", "Bioenergy feedstocks",
  "CARIW", "Carinata winter type", "Bioenergy feedstocks",
  "CARR", "Carrot", "Vegetables",
  "CASH", "Cashew", "Oil crops",
  "CASV", "Cassava", "Roots and tubers",
  "CAST", "Castor bean", "Oil crops",
  "CHCK", "Chickpea", "Pulses",
  "CITR", "Citrus", "Fruits",
  "COCN", "Coconut", "Fruits",
  "COFF", "Coffee (the better of arabica and robusta)", "Narcotics and stimulants",
  "COFA", "Coffee arabica", "Narcotics and stimulants",
  "COFR", "Coffee robusta", "Narcotics and stimulants",
  "COTT", "Cotton", "Industrial crops",
  "COWP", "Cowpea", "Pulses",
  "DPEA", "Dry peas", "Pulses",
  "RICD", "Dryland rice", "Cereals",
  "COC3", "Dwarf coconut", "Fruits",
  "ECAN", "Energy cane", "Bioenergy feedstocks",
  "ECANV2", "Energy cane v2", "Bioenergy feedstocks",
  "ECANV3", "Energy cane v3", "Bioenergy feedstocks",
  "FIMLT", "Finger Millet", "Cereals",
  "FLAX", "Flax fibre", "Industrial crops",
  "FONI", "Fonio", "Cereals",
  "FMLT", "Foxtail millet", "Cereals",
  "GRAM", "Gram", "Pulses",
  "GYAM", "Greater yam", "Roots and tubers",
  "GRND", "Groundnut", "Oil crops",
  "HMZE", "Highland maize (tropics)", "Cereals",
  "HSRG", "Highland sorghum (tropics)", "Cereals",
  "COC2", "Hybrid coconut", "Fruits",
  "JATR", "Jatropha", "Bioenergy feedstocks",
  "LMZE", "Lowland maize", "Cereals",
  "LSRG", "Lowland sorghum", "Cereals",
  "MCAU2", "Macauba palm, inter-cropping", "Bioenergy feedstocks",
  "MCAU", "Macauba palm, single cropping", "Bioenergy feedstocks",
  "MAIZ", "Maize (best of lmze, hmze and tmze)", "Cereals",
  "MANGO", "Mango", "Fruits",
  "MLLT", "Millet (better of fmlt and pmlt)", "Cereals",
  "MISC", "Miscanthus", "Bioenergy feedstocks",
  "NAPR", "Napier grass", "Fodder crops",
  "OATS", "Oat", "Cereals",
  "OILP", "Oil palm", "Oil crops",
  "OKRA", "Okra", "Vegetables",
  "OLIV", "Olive", "Oil crops",
  "ONIO", "Onion", "Vegetables",
  "PRUB", "Para-rubber", "Industrial crops",
  "GRAS", "Pasture grasses", "Fodder crops",
  "GRLG", "Pasture legumes", "Fodder crops",
  "PMLT", "Pearl millet", "Cereals",
  "BEAN", "Phaseolous bean", "Pulses",
  "PIGP", "Pigeon pea", "Pulses",
  "RAPE", "Rapeseed", "Oil crops",
  "RCGR", "Reed canary grass", "Bioenergy feedstocks",
  "RYES", "Rye (the better of srye and wrye)", "Cereals",
  "SESA", "Sesame", "Oil crops",
  "MZSI", "Silage maize", "Fodder crops",
  "SOLA", "Solaris Tobacco", "Bioenergy feedstocks",
  "SORG", "Sorghum (best of lsrg, hsrg and tsrg)", "Cereals",
  "SOYB", "Soybean", "Oil crops",
  "SBRL", "Spring barley", "Cereals",
  "SRYE", "Spring rye", "Cereals",
  "SWHE", "Spring wheat", "Cereals",
  "SUGB", "Sugar beet", "Sugar crops",
  "SUGC", "Sugar cane", "Sugar crops",
  "SUNF", "Sunflower", "Oil crops",
  "SPOT", "Sweet potato", "Roots and tubers",
  "SWGR", "Switchgrass", "Bioenergy feedstocks",
  "COC1", "Tall coconut", "Fruits",
  "CYAM3", "Tannia (Xanthosoma sagittifolium)", "Roots and tubers",
  "CYAM1", "Taro, dryland (Colocasia esculenta)", "Roots and tubers",
  "CYAM2", "Taro, wetland (Colocasia esculenta)", "Roots and tubers",
  "TEAS", "Tea (best of China, Assam and hybrid types)", "Narcotics and stimulants",
  "TEFF", "Tef", "Cereals",
  "TMZE", "Temperate/sub-tropical maize", "Cereals",
  "TSRG", "Temperate/sub-tropical sorghum", "Cereals",
  "TOBA", "Tobacco", "Narcotics and stimulants",
  "TOMA", "Tomato", "Vegetables",
  "TRIT", "Triticale", "Bioenergy feedstocks",
  "WMEL", "Watermelon", "Fruits",
  "RICW", "Wetland rice", "Cereals",
  "WHEA", "Wheat (the better of swhe and wwhe)", "Cereals",
  "WPOT", "White potato", "Roots and tubers",
  "WYAM", "White yam", "Roots and tubers",
  "WRYE", "Winter rye", "Cereals",
  "WBRL", "Winter, sub-tropical and tropical highland barley", "Cereals",
  "WWHE", "Winter, sub-tropical and tropical highland wheat", "Cereals",
  "YAMS", "Yam (best of wyam, gyam, yyam)", "Roots and tubers",
  "YYAM", "Yellow yam", "Roots and tubers"
) |>
  mutate(gaez_theme = 3)

# Module V (3-letter codes) - Theme 4
gaez_crops_m5 <- tribble(
  ~gaez_crop_code, ~name, ~gaez_crop_group,
  "ALF", "Alfalfa", "Fodder crops",
  "BAN", "Banana", "Fruits",
  "BRL", "Barley", "Cereals",
  "BSG", "Biomass sorghum", "Bioenergy feedstocks",
  "BCH", "Brachiaria", "Bioenergy feedstocks",
  "BCK", "Buckwheat", "Cereals",
  "CAB", "Cabbage", "Vegetables",
  "CAM", "Camelina", "Bioenergy feedstocks",
  "CRT", "Carinata", "Bioenergy feedstocks",
  "CAR", "Carrot", "Vegetables",
  "CSH", "Cashew", "Oil crops",
  "CSV", "Cassava", "Roots and tubers",
  "CST", "Castor bean", "Oil crops",
  "CHK", "Chickpea", "Pulses",
  "CIT", "Citrus", "Fruits",
  "COC", "Cocoa", "Narcotics and stimulants",
  "CON", "Coconut", "Fruits",
  "COF", "Coffee", "Narcotics and stimulants",
  "COT", "Cotton", "Industrial crops",
  "COW", "Cowpea", "Pulses",
  "PEA", "Dry pea", "Pulses",
  "RCD", "Dryland rice", "Cereals",
  "ECN", "Energy cane (better of Energy cane Type Vertix 2 and Vertix 3)", "Bioenergy feedstocks",
  "EC2", "Energy cane Type Vertix 2 (developed by GranBio)", "Bioenergy feedstocks",
  "EC3", "Energy cane Type Vertix3 (developed by GranBio)", "Bioenergy feedstocks",
  "FLX", "Flax", "Industrial crops",
  "FML", "Foxtail millet", "Cereals",
  "GRM", "Gram", "Pulses",
  "GRD", "Groundnut", "Oil crops",
  "JTR", "Jatropha", "Bioenergy feedstocks",
  "MCA", "Macauba palm", "Bioenergy feedstocks",
  "MZE", "Maize", "Cereals",
  "MNG", "Mango", "Fruits",
  "MIS", "Miscanthus", "Bioenergy feedstocks",
  "NAP", "Napier grass", "Fodder crops",
  "OAT", "Oat", "Cereals",
  "OLP", "Oil palm", "Oil crops",
  "OLV", "Olive", "Oil crops",
  "ONI", "Onion", "Vegetables",
  "PML", "Pearl millet", "Cereals",
  "PHB", "Phaseolus bean", "Pulses",
  "PIG", "Pigeonpea", "Pulses",
  "RSD", "Rapeseed", "Oil crops",
  "RCG", "Reed canary grass", "Bioenergy feedstocks",
  "RUB", "Rubber", "Industrial crops",
  "RYE", "Rye", "Cereals",
  "SES", "Sesame", "Oil crops",
  "MZS", "Silage maize", "Cereals",
  "SOL", "Solaris energy tobacco", "Bioenergy feedstocks",
  "SRG", "Sorghum", "Cereals",
  "SOY", "Soybean", "Oil crops",
  "SUB", "Sugar beet", "Sugar crops",
  "SUC", "Sugar cane", "Sugar crops",
  "SFL", "Sunflower", "Oil crops",
  "SPO", "Sweet potato", "Roots and tubers",
  "SWG", "Switchgrass", "Bioenergy feedstocks",
  "CYA", "Taro", "Roots and tubers",
  "TEA", "Tea", "Narcotics and stimulants",
  "TOB", "Tobacco", "Narcotics and stimulants",
  "TOM", "Tomato", "Vegetables",
  "TRI", "Triticale", "Bioenergy feedstocks",
  "RCW", "Wetland rice", "Cereals",
  "WHE", "Wheat", "Cereals",
  "WPO", "White potato", "Roots and tubers",
  "YAM", "Yam", "Roots and tubers"
) |>
  mutate(gaez_theme = 4)

# Module VI (3-letter codes) - Theme 5
gaez_crops_m6_t5 <- tribble(
  ~gaez_crop_code, ~name,
  "NES", "All other crops not elsewhere included (mainly spices, fibre crops)",
  "BAN", "Banana and Plantain",
  "BRL", "Barley",
  "CSV", "Cassava",
  "COC", "Cocoa",
  "CON", "Coconut",
  "COF", "Coffee",
  "FDD", "Fodder crops",
  "FRT", "Fruits and Nuts",
  "GRD", "Groundnuts (with shell)",
  "MZE", "Maize",
  "MLT", "Millet",
  "OLP", "Oil palm fruit",
  "OOC", "Olives and other minor oil crops",
  "OCE", "Other cereals (oats, rye, buckwheat and other minor grains)",
  "OVG", "Other vegetables (i.e. all vegetables except tomato)",
  "RUB", "Para rubber",
  "PLS", "Pulses",
  "RSD", "Rapeseed",
  "RCW", "Rice",
  "COT", "Seed cotton",
  "SES", "Sesame seed",
  "SRG", "Sorghum",
  "SOY", "Soybean",
  "SUB", "Sugar beet",
  "SUC", "Sugarcane",
  "SFL", "Sunflower seed",
  "TEA", "Tea & Mate leaves",
  "TOB", "Tobacco leaves",
  "TOM", "Tomato",
  "WHE", "Wheat",
  "POT", "White potato, Sweet potato",
  "ORT", "Yams (and other minor root crops)",
  "ALL", "All crops (1-33)",
  "MAJ", "Major crops (1-9, 11,12, 14-20, 22-24)",
  "CER", "Cereal crops (1-7)",
  "OIL", "Oil crops (14-20)",
  "RTS", "Root and tuber crops (8-9)"
) |>
  mutate(gaez_theme = 5, gaez_crop_group = NA_character_)

# Module VI (3-letter codes) - Theme 6
gaez_crops_m6_t6 <- tribble(
  ~gaez_crop_code, ~name,
  "GAP", "All crops",
  "BAN", "Banana and Plantain",
  "BRL", "Barley",
  "CSV", "Cassava",
  "GCE", "Cereal crops",
  "COT", "Cotton",
  "GRD", "Groundnut",
  "MZE", "Maize",
  "MLT", "Millet",
  "GOI", "Oil crops",
  "OLP", "Oil palm fruit",
  "OCE", "Other cereals (oats, rye, buckwheat and other minor grains)",
  "RSD", "Rapeseed",
  "RCW", "Rice",
  "GRT", "Root and tuber crops",
  "SES", "Sesame seed",
  "SRG", "Sorghum",
  "SOY", "Soybean",
  "SUB", "Sugar beet",
  "SUC", "Sugarcane",
  "SFL", "Sunflower seed",
  "TOB", "Tobacco leaves",
  "WHE", "Wheat",
  "POT", "White potato, Sweet potato"
) |>
  mutate(gaez_theme = 6, gaez_crop_group = NA_character_)

# Combine all crop tables
gaez_crops <- bind_rows(
  gaez_crops_m2,
  gaez_crops_m5,
  gaez_crops_m6_t5,
  gaez_crops_m6_t6
)

# ==============================================================================
# GAEZ v5 Scenarios (Time periods, Climate models, SSPs, Water management)
# ==============================================================================

gaez_scenarios <- tribble(
  ~time_period, ~description, ~start_year, ~end_year,
  "HP8100", "Historical Period 1981-2000", 1981, 2000,
  "HP0120", "Historical Period 2001-2020", 2001, 2020,
  "FP2140", "Future Period 2021-2040", 2021, 2040,
  "FP4160", "Future Period 2041-2060", 2041, 2060,
  "FP6180", "Future Period 2061-2080", 2061, 2080,
  "FP8100", "Future Period 2081-2100", 2081, 2100
) |>
  bind_rows(tribble(
    ~climate_model, ~description,
    "AGERA5", "AgERA5 climate data",
    "GFDL-ESM4", "GFDL-ESM4 climate model",
    "IPSL-CM6A-LR", "IPSL-CM6A-LR climate model",
    "MPI-ESM1-2-HR", "MPI-ESM1-2-HR climate model",
    "MRI-ESM2-0", "MRI-ESM2-0 climate model",
    "UKESM1-0-LL", "UKESM1-0-LL climate model",
    "ENSEMBLE", "Multi-model ensemble"
  )) |>
  bind_rows(tribble(
    ~ssp, ~description,
    "HIST", "Historical scenario",
    "SSP126", "Shared Socioeconomic Pathway 1-2.6",
    "SSP370", "Shared Socioeconomic Pathway 3-7.0",
    "SSP585", "Shared Socioeconomic Pathway 5-8.5"
  )) |>
  bind_rows(tribble(
    ~water_management_code, ~description,
    "HRLM", "High input, Rain-fed, Low management",
    "HILM", "High input, Irrigated, Low management",
    "LRLM", "Low input, Rain-fed, Low management",
    "LILM", "Low input, Irrigated, Low management"
  )) |>
  bind_rows(tribble(
    ~water_supply, ~description,
    "WSI", "Water supply - Irrigated",
    "WSR", "Water supply - Rain-fed",
    "WST", "Water supply - Total"
  ))

# ==============================================================================
# GAEZ v5 URL Structure
# ==============================================================================

gaez_url_structure <- tribble(
  ~theme, ~filename_parts,
  # Theme 1: Static maps (land resources, soils, terrain)
  1, list(c("variable_code")),
  # Theme 2: Agro-climatic resources (temperature, precipitation, etc.)
  2, list(c("variable_code", "time_period", "climate_model", "ssp")),
  # Theme 3: Agro-climatic potential yield (4-letter crop codes)
  3, list(c("variable_code", "time_period", "climate_model", "ssp", "crop", "water_management")),
  # Theme 4: Suitability & attainable yield (3-letter crop codes) - most common
  4, list(c("variable_code", "time_period", "climate_model", "ssp", "crop", "water_management")),
  # Theme 5: Actual yields & production
  5, list(c("variable_code", "crop", "water_supply")),
  # Theme 6: Yield & production gaps
  6, list(c("variable_code", "crop", "water_supply")),
  # Theme 9: Time series variants
  9, list(c("variable_code", "year"))
)

# ==============================================================================
# Save all data objects as INTERNAL package data (R/sysdata.rda)
# ==============================================================================
# This makes the data available to package functions but not directly exported
# to users. Users can still access via helper functions.

usethis::use_data(
  gaez_variables,
  gaez_crops,
  gaez_scenarios,
  gaez_url_structure,
  internal = TRUE,
  overwrite = TRUE,
  compress = "xz"
)

message("\n=== All data objects saved to R/sysdata.rda ===")
